### ISSUE TITLE
How to import custom shapes? 

### ISSUE THREAD

**Issue by Victorcangil** [TimHuisman1703/ComplexFourier#1]
How can we add custom shapes to this? Like extract it from a custom SVG
Thanks

**Comment by TimHuisman1703** [comment]
Importing SVG's is not supported, as I made this project solely for the purpose of drawing A01, which only needs vertical and horizontal lines and arcs with an angle of pi/2.
I'm also not going to update it, because this was a fun little project, and I don't want it to turn into something I need to maintain/update.

However, if you can pin down the points you want the line to trace, you can generate your own coords.txt file, and then run solve.py and render.py to generate your video.

Note that the video shows coordinates from (0, 0) to (1919, 1079), so if you create the coord.txt file yourself, make sure that the coordinates are properly scaled and translated. I suggest running render.py with VIDEO_RENDER = False and checking out.svg to get the shape right before actually rendering the entire video, since I haven't optimized that and it takes long.
